spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://192.168.47.129:3306/highperf
    driver-class-name: com.mysql.cj.jdbc.Driver

#    用yml来配置datasource比properties排版好很多,所以...

